
### Get Branches
GET https://dbresto-api.designbluemanila.com/api/frontend/branches

### Get Menu
GET https://dbresto-api.designbluemanila.com/api/frontend/branch/makati/menu

### Get Makati
GET https://dbresto-api.designbluemanila.com/api/frontend/homepage/makati

### Get dish
GET https://dbresto-api.designbluemanila.com/api/frontend/branch/makati/samgyeopsal-hansang